### ISSUE TITLE
縦書き mode

### ISSUE THREAD

**Issue by cashewnuttynuts** [themoeway/yomitan#594]
for the authentic 国語辞典 experience

**Comment by Kuuuube** [comment]
If you really want you could add some css to some things like this (maybe in a few other places too idk):

```css
.headword-term {
    writing-mode: vertical-rl;
    text-orientation: mixed;
}
```

But I don't see this getting added as a specific setting.
