### ISSUE TITLE
Allow Adding Duplicates to be Disabled

### ISSUE THREAD

**Issue by kanjieater** [themoeway/yomitan#826]
Core functionality change with the allowing for duplicates feature, as mentioned here https://github.com/themoeway/yomitan/issues/818#issuecomment-2058060331

You used to be able to prevent duplicates from being added to the same deck, but now you can't. Ideally we would be able to set a setting that would Disable Adding Duplicates entirely. 

At the very least a debounce on the Add Card button that transitions to the Add Duplicate button would be a welcome addition as well

**Comment by kanjieater** [comment]
You can work around this currently by using
![image](https://github.com/themoeway/yomitan/assets/32607317/0a3169cf-82ee-4ecc-a2c9-fde7c30968de)
However the Alt+E will still pick up the duplicate, so this is only to prevent users clicking
```
button.action-button[title="Add duplicate expression (Alt + E)"] {
    display: none;
}```

**Comment by Kuuuube** [comment]
Cooked up some much better css for this:

```css
.icon[data-icon="add-duplicate-term-kanji"] {
    background-image: url('/images/add-term-kanji.svg');
    opacity: 0.25;
}

button.action-button[title="Add duplicate expression (Alt + E)"] {
    pointer-events: none;
}

.icon[data-icon="add-duplicate-term-kana"] {
    background-image: url('/images/add-term-kana.svg');
    opacity: 0.25;
    pointer-events: none;
}

button.action-button[title="Add duplicate reading (Alt + R)"] {
    pointer-events: none;
}
```

It should exactly restore the look and function of the old buttons. The "add dupe" buttons will show as grayed out green buttons instead of red and you will not be able to click them.

Tempted to close this issue since I don't see an actual option for switching it back to the old button ever being added (was already discussed when deciding to add the red "add dupe" buttons) but will leave it open for now since the debounce part has some potential use cases.
